// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQDx0iOcmFYNALYGxdXNqWSmLUrJlAd_c',
    appId: '1:617931135562:web:ce0e7f63a867cf2968a4b3',
    messagingSenderId: '617931135562',
    projectId: 'e-commerce-flutter-82a2f',
    authDomain: 'e-commerce-flutter-82a2f.firebaseapp.com',
    storageBucket: 'e-commerce-flutter-82a2f.appspot.com',
    measurementId: 'G-D5GJ1BFRHQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDkBeCehyvmUJy1F9hSTWP-oY48cCgslpg',
    appId: '1:617931135562:android:4e9febce6d07bc7d68a4b3',
    messagingSenderId: '617931135562',
    projectId: 'e-commerce-flutter-82a2f',
    storageBucket: 'e-commerce-flutter-82a2f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBsFQOisR8nIbHQBWBW2kYKNK0Fs6RAQK0',
    appId: '1:617931135562:ios:0fb5520dd687e78268a4b3',
    messagingSenderId: '617931135562',
    projectId: 'e-commerce-flutter-82a2f',
    storageBucket: 'e-commerce-flutter-82a2f.appspot.com',
    iosClientId: '617931135562-hnfpthrtt5lu2m2ds2vcmrvnbnpgdjl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBsFQOisR8nIbHQBWBW2kYKNK0Fs6RAQK0',
    appId: '1:617931135562:ios:0fb5520dd687e78268a4b3',
    messagingSenderId: '617931135562',
    projectId: 'e-commerce-flutter-82a2f',
    storageBucket: 'e-commerce-flutter-82a2f.appspot.com',
    iosClientId: '617931135562-hnfpthrtt5lu2m2ds2vcmrvnbnpgdjl8.apps.googleusercontent.com',
    iosBundleId: 'com.example.ecommerce',
  );
}
